/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatWindow: typeof import('./src/components/ChatWindow.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputBox: typeof import('./src/components/InputBox.vue')['default']
    MessageItem: typeof import('./src/components/MessageItem.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    SplashScreen: typeof import('./src/components/SplashScreen.vue')['default']
  }
}
